workflows:
  flutter-workflow:
    name: Flutter Build Workflow
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_VERSION: stable
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run Flutter tests
        script: |
          flutter test
      - name: Build Android app
        script: |
          flutter build apk --release
      - name: Build iOS app (no codesign)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - seryojabaulin25@gmail.com
